
const path = require('path');
const HTMLWebpackplugin = require('html-webpack-plugin');
const data = require('./dataset.json');



module.exports = {
    mode: 'development',
    entry: './src/index.js',
    devServer: {
        static: './dist',
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
        assetModuleFilename: 'img/[name][ext]',
    },
    plugins: [
        new HTMLWebpackplugin({
            title: data.page_meta.title,
            meta: {
                keywords: data.page_meta.meta_keywords,
                description: data.page_meta.meta_description,
            },
            template: './src/index.html',
            templateParameters: {
                'H1': data.page_meta.h1,
                'breadcrumbOne': data.breadcrumbs[0].text,
                'breadcrumbTwo': data.breadcrumbs[1].text,
                'breadcrumbActive': data.breadcrumbs[2].text,
                'navLinkOne': data.nav[0].text,
                'navLinkTwo': data.nav[1].text,
                'navLinkThree': data.nav[2].text,
                'navLinkFour': data.nav[3].text,
                'navLinkOneHref': data.nav[0].href,
                'navLinkTwoHref': data.nav[1].href,
                'navLinkThreeHref': data.nav[2].href,
                'navLinkFourHref': data.nav[3].href,
                'breadcrumbOneLink': data.breadcrumbs[0].href,
                'breadcrumbTwoLink': data.breadcrumbs[1].href,
                'itemTitleOne': data.stock[0].title,
                'itemTitleTwo': data.stock[1].title,
                'itemTitleThree': data.stock[2].title,
                'itemTitleFour': data.stock[3].title,
                'itemTitleFive': data.stock[4].title,
                'itemTitleSix': data.stock[5].title,
                'currencyOne': data.stock[0].price_currency,
                'currencyTwo': data.stock[1].price_currency,
                'currencyThree': data.stock[2].price_currency,
                'currencyFour': data.stock[3].price_currency,
                'currencyFive': data.stock[4].price_currency,
                'currencySix': data.stock[5].price_currency,
                'priceOne': data.stock[0].price,
                'priceTwo': data.stock[1].price,
                'priceThree': data.stock[2].price,
                'priceFour': data.stock[3].price,
                'priceFive': data.stock[4].price,
                'priceSix': data.stock[5].price,
                'yearOne': data.stock[0].year,
                'yearTwo': data.stock[1].year,
                'yearThree': data.stock[2].year,
                'yearFour': data.stock[3].year,
                'yearFive': data.stock[4].year,
                'yearSix': data.stock[5].year,
                'mileageOne': data.stock[0].mileage,
                'mileageMeasureOne': data.stock[0].mileage_measure,
                'mileageTwo': data.stock[1].mileage,
                'mileageMeasureTwo': data.stock[1].mileage_measure,
                'mileageThree': data.stock[2].mileage,
                'mileageMeasureThree': data.stock[2].mileage_measure,
                'mileageFour': data.stock[3].mileage,
                'mileageMeasureFour': data.stock[3].mileage_measure,
                'mileageFive': data.stock[4].mileage,
                'mileageMeasureFive': data.stock[4].mileage_measure,
                'mileageSix': data.stock[5].mileage,
                'mileageMeasureSix': data.stock[5].mileage_measure,
                'axleConfigurationOne': data.stock[0].axle_configuration,
                'axleConfigurationTwo': data.stock[1].axle_configuration,
                'axleConfigurationThree': data.stock[2].axle_configuration,
                'axleConfigurationFour': data.stock[3].axle_configuration,
                'axleConfigurationFive': data.stock[4].axle_configuration,
                'axleConfigurationSix': data.stock[5].axle_configuration,
                'itemHrefOne': data.stock[0].href,
                'itemHrefTwo': data.stock[1].href,
                'itemHrefThree': data.stock[2].href,
                'itemHrefFour': data.stock[3].href,
                'itemHrefFive': data.stock[4].href,
                'itemHrefSix': data.stock[5].href,
                'TextParOne': data.page_text[0].content,
                'TextParTwo': data.page_text[1].content,
                'TextParThree': data.page_text[2].content,
                'tagOne': data.page_text[0].tag,
                'tagTwo': data.page_text[1].tag,
                'tagThree': data.page_text[2].tag,
                'typeOne': data.stock[0].type,
                'powerOne': data.stock[0].power,
                'powerMeassureOne': data.stock[0].power_measure,
                'PayloadOne': data.stock[0].payload,
                'GrossWeightOne': data.stock[0].gross_weight,
                'typeTwo': data.stock[1].type,
                'powerTwo': data.stock[1].power,
                'powerMeassureTwo': data.stock[1].power_measure,
                'PayloadTwo': data.stock[1].payload,
                'GrossWeightTwo': data.stock[1].gross_weight,
                'typeThree': data.stock[2].type,
                'powerThree': data.stock[2].power,
                'powerMeassureThree': data.stock[2].power_measure,
                'PayloadThree': data.stock[2].payload,
                'GrossWeightThree': data.stock[2].gross_weight,
                'typeFour': data.stock[3].type,
                'powerFour': data.stock[3].power,
                'powerMeassureFour': data.stock[3].power_measure,
                'PayloadFour': data.stock[3].payload,
                'GrossWeightFour': data.stock[3].gross_weight,
                'typeFive': data.stock[4].type,
                'powerFive': data.stock[4].power,
                'powerMeassureFive': data.stock[4].power_measure,
                'PayloadFive': data.stock[4].payload,
                'GrossWeightFive': data.stock[4].gross_weight,
                'typeSix': data.stock[5].type,
                'powerSix': data.stock[5].power,
                'powerMeassureSix': data.stock[5].power_measure,
                'PayloadSix': data.stock[5].payload,
                'GrossWeightSix': data.stock[5].gross_weight,
                'img1': data.stock[0].image,
                'img2': data.stock[1].image,
                'img3': data.stock[2].image,
                'img4': data.stock[3].image,
                'img5': data.stock[4].image,
                'img6': data.stock[5].image,
              },
        }),
    ],
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/i,
                use: ['style-loader', 'css-loader', 'sass-loader'],
            },
            {
                test: /\.(|png|svg|jpe?g|gif)$/i,
                type: 'asset/resource'
            },
        ],
    },
}